version: "3"
services:
  app:
    image: azure-queue-to-file-python
    volumes:
      - ./:/usr/local/app
      - /data-export/output:/data-export/output
    working_dir: /usr/local/app
    command: python consumer.py